// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ukg2CBH5D2I_YyWP35t4xvZ4_CqCN7c',
    appId: '1:950294203208:web:6c77a3e8410c66f43ac17d',
    messagingSenderId: '950294203208',
    projectId: 'medlink-1f772',
    authDomain: 'medlink-1f772.firebaseapp.com',
    storageBucket: 'medlink-1f772.firebasestorage.app',
    measurementId: 'G-86DYJW3VJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVfmEEc2U0pcfjQXp_7TUOg-KNAe2aF4',
    appId: '1:950294203208:android:613267b66bf7f54c3ac17d',
    messagingSenderId: '950294203208',
    projectId: 'medlink-1f772',
    storageBucket: 'medlink-1f772.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ukg2CBH5D2I_YyWP35t4xvZ4_CqCN7c',
    appId: '1:950294203208:web:4ac955c929e1e4833ac17d',
    messagingSenderId: '950294203208',
    projectId: 'medlink-1f772',
    authDomain: 'medlink-1f772.firebaseapp.com',
    storageBucket: 'medlink-1f772.firebasestorage.app',
    measurementId: 'G-93H0RRM0Z8',
  );
}
